[build]
  publish = "public"
  command = "cd themes/ananke && npm install && cd ../.. && hugo"

[context.production.environment]
  NODE_VERSION = "23.11.0"
  HUGO_VERSION = "0.145.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
